spring.application.name=conversor-moeda
logging.level.root=INFO
logging.level.com.seupacote=DEBUG
logging.level.org.springframework=INFO
logging.level.org.apache.catalina=WARN
logging.level.org.springframework.boot.autoconfigure=WARN
logging.level.org.springframework.web=INFO
spring.cache.type=jcache
spring.cache.jcache.config=classpath:ehcache.xml


